// ==UserScript==
// @name         四川公需科目精英人才答题辅助脚本
// @namespace    http://tampermonkey.net/
// @version      0.17
// @description  查询并显示试题参考答案
// @icon         https://www.sedu.net/apppc/login/static/jjw-bj-bf11c0d7.png
// @match        https://jyrcjypt.zgzjzj.com/learncenter/practice
// @match        https://jyrcjypt.zgzjzj.com/examination/perpar.html
// @downloadURL  https://life5211.github.io/web/auto/answer.zgzjzj.user.js
// @updateURL    https://life5211.github.io/web/auto/answer.zgzjzj.user.js
// @noframes
// @grant        unsafeWindow
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_log
// ==/UserScript==

(function () {
  let $q = (s) => document.querySelector(s),
    $qa = (s) => Array.from(document.querySelectorAll(s));
  function show(ans, qs) {
    let div = document.createElement("div");
    div.innerHTML = `<pre class="answer" style="background: #ccc;white-space: pre;">${ans}</pre>`;
    qs.insertBefore(div, qs.firstChild);
  }
  document.ansI = setInterval((_) => {
    $qa("div.question_index").forEach((qs) => {
      if (qs.querySelector("pre.answer")) return;
      let ques = qs.querySelector("p")?.innerText;
      if (!ques) return console.error("未找到题目");
      ques = ques
        .replace(qs.querySelector("span").innerText, "")
        .replace(/\(\d+分\)/, "")
        .replaceAll(/\s/g, "");
      let rst = document.qas.filter(
        (qa) => qa.q.trim().replaceAll(/\s/g, "") === ques
      );
      if (rst.length) return show(JSON.stringify(rst, null, "\t"), qs);
    });
    $qa("div.topic_chioseItem").forEach((qs) => {
      if (qs.querySelector("pre.answer")) return;
      let ques = qs.querySelector("span.topic_itemText")?.innerText;
      if (!ques) return console.error("未找到题目");
      let rst = document.qas.filter(
        (qa) =>
          qa.q.trim().replaceAll(/\s/g, "") === ques.trim().replaceAll(/\s/g, "")
      );
      if (rst.length) return show(JSON.stringify(rst, null, "\t"), qs);
    });
  }, 1000);
})();

document.qas = [
  {
    tType: 1,
    answer: "D",
    choose: "智能物流;智能安防;智能控制;智能交通",
    id: 487825,
    content:
      "通过交通信息采集系统采集道路中的车辆流量、行车速度等信息，经智能系统分析后调整各路口红绿灯时长属于人工智能在（  ）领域的应用。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "迎宾机器人;搬运机器人;货架穿梭车;分拣机器人",
    id: 487826,
    content: "下面不是应用于智能物流领域的机器人是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "70%;50%;30%;100%",
    id: 487827,
    content:
      "在测试人与被测试者（一个人和一台机器）隔开的情况下，通过-些装置（如键盘）向被测试者随意提问。经过多次测试后，如果被测试者超过（  ）的答复不能使测试人确认出哪个是人、哪个是机器的回答，那么这台机器就通过了测试，并被认为具有人类智能。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "人脸识别;3D识别;虹膜识别;声纹识别",
    id: 487828,
    content:
      "生物特征识别技术是指通过个体生理特征或行为特征对个体身份进行识别认证的技术。下列技术不属于生物特征识别技术的是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose:
      "能模拟教师教学的经验和方法，对同学们实施一对一的教学;能跟踪、记录和分析学习者学习过程和结果，并据此推送、传递知识;能利用大数据技术分析学习者的情感、爱好，让学习者戒除各种恶习;能利用大数据技术分析学习者学习情况，为每一名学习者选择合适的学习资源，制订个性化的学习方案",
    id: 487829,
    content:
      "人工智能在学习领域有广泛应用。下述关于人工智能的说法不确定的是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "物理;化学;数学;生物",
    id: 487830,
    content: "第一例专家系统是在（  ）领域发挥作用的。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "理论;方法;技术;应用",
    id: 487831,
    content:
      "人工智能，是研究、开发用于模拟、延伸和扩展人的智能的（  ）系统的一门新的技术科学。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "共同的态势感知;共同的演化模型;共同的行动规范;共同的价值观",
    id: 487832,
    content: "认知架构实现的四个对齐：（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ACD",
    choose: "技术突破;应用突破;算力的重要性;多模态与具身智能",
    id: 487833,
    content: "通用人工智能技术发展趋势是（  ）？",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose: "技术发展;政策导向;应用需求;理论支持",
    id: 487834,
    content: "Transformer架构的重构受到（  ）因素的影响？",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "AB",
    choose: "计算力的提升;大量数据驱动;社会关注度提升;人类专家规则的完善",
    id: 487835,
    content: "发展出图像识别成功率超越人类的人工智能的主要因素有（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose: "AI瓶颈;性能有限;缺乏“常识”;财政问题",
    id: 487836,
    content: "人工智能研究第一次寒冬的发生主要原因有（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 487837,
    content:
      "通用人工智能，是指具有高效的学习和泛化能力、能够根据所处的复杂动态环境自主产生并完成任务的通用人工智能体。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 487838,
    content: "认知计算：大量数据的关联规则学习、聚类和预测分析等技术。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 487839,
    content:
      "符号主义（Symbolism）：强调模拟人脑的神经网络结构，深度学习是连接主义的一个现代例子。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 487840,
    content:
      "算法创新：新的算法如自监督学习、对比学习、图神经网络等的发展，为Transformer架构的改进提供了新的思路和方法。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 487841,
    content:
      "计算机视觉：计算机视觉使计算机能够理解和解析视觉信息，如图像和视频。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 487842,
    content:
      "集成主义（Integrationism）：试图将不同的AI技术和方法结合起来，以创建更加强大和灵活的智能系统。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "2017;2018;2019;2020",
    id: 496985,
    content: "（  ）年10月22日，国务院颁布《优化营商环境条例》。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "标准化;国际化;一体化;规范化",
    id: 496986,
    content:
      "党的二十大报告指出，高质量发展是全面建设社会主义现代化国家的首要任务，要营造市场化、法治化、（  ）流营商环境。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "世界银行;国际货币基金组织;国际清算银行;世界贸易组织",
    id: 496987,
    content:
      "（  ）从2003年起每年开展评价，对参评经济体营商环境便利度进行评分和排名，并发布《营商环境报告》。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "民营企业;国有企业;市场主体和社会公众;群众",
    id: 496988,
    content:
      "国家发展改革委国家发展改革委：建立了为（  ）满意度导向的中国营商环境评价体系。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "政务服务;知识产权保护;市场监管;包容普惠创新",
    id: 496989,
    content:
      "中国营商环境评价指标体系设置了（  ）等中国特色指标，更加准确完整反映各地方营商环境优劣。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "便利性;公平性;透明度;法治化",
    id: 496990,
    content: "以下哪些选项是好的营商环境的特点（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 496991,
    content: "2023年11月，国家政务服务平台整体上线试运行。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 496992,
    content:
      "公平性强的营商环境，可保证市场公平竞争，优胜劣汰，激发各类市场主体的活力和创造力，提高资源配置效率。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 496993,
    content:
      "世界银行认为，“营商环境”就是在一国（或地区）创办和经营企业的难易程度。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 496994,
    content:
      "知识产权是企业产权的重要组成部分。充分有效地保护知识产权能提升企业创新的积极性，是优化营商环境的重要方面。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "领导者;执行者;执政官;调停者",
    id: 497283,
    content:
      "（  ）是依据其承担的角色与分配的职责来激励和影响人们实现组织目标的人。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "个人领导力;团队领导力;组织领导力;目标领导力",
    id: 497284,
    content: "领导力不包括下列哪项（  ）个人领导力、团队领导力与组织领导力",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "能作能为;善作善为;善作善成;优柔寡断",
    id: 497285,
    content: "作为领导干部，要始终重视能力本领提升，其中不包括（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "目标激励;生活激励;情感激励;待遇激励",
    id: 497286,
    content: "激励的要决中不包括（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "信念坚定;为民服务;勤政务实;敢于担当",
    id: 497287,
    content: "新时代“好干部”标准有（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "AB",
    choose: "自尊心;自信心;自强;自立",
    id: 497288,
    content: "苏格拉底说：一个人能否有成就，只看他是否具备（  ）两个条件。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497289,
    content: "目标信仰是领导力的源动力。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 497290,
    content: "领导的重要性在于带来希望。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497291,
    content:
      "领导力提升没有捷径可走，必须立足岗位，加强思想淬炼、政治历练、实践锻炼与专业训练，层层修炼“内功”。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497292,
    content: "自尊有强弱之分，过强则成虚荣心，过弱则变成自卑。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "汉斯·薛利;斯金纳;塞利格曼;津巴多",
    id: 497176,
    content:
      "压力这一概念最早是在1936年由加拿大著名内分泌专家（  ）博士提出的，因此他被称为“压力之父”。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "无序阶段;安定阶段;冲击阶段;解决问题阶段",
    id: 497177,
    content: "压力反应在行为反应的第一阶段为（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "感觉;交往;直觉;知觉",
    id: 497178,
    content:
      "世界卫生组织认为，健康是一种身体、精神和（  ）上的完美状态，而不只是身体无病。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "认知;心情;行为;心境",
    id: 497179,
    content: "（  ）是情绪的背景、底色或基调。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ACD",
    choose: "持久的;具体的;稳定的;相对隐蔽",
    id: 497180,
    content: "心境则是（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "强迫思维;强迫情绪;强迫意向;强迫行为",
    id: 497181,
    content: "强迫症有（  ）和强迫动作等表现。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497182,
    content: "心理健康的标准应考察整体的协调性。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497183,
    content:
      "适度的压力是维持人们正常的心理功能和生理功能的必要条件，同时有助于人们适应环境、提高能力。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 497184,
    content: "压力只是心事,与身体无关。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497185,
    content: "心理健康是一种动态的平衡。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "2019;2018;2020;2021",
    id: 497191,
    content:
      "我国在（  ）年明确了数据是与土地、劳动、资本、技术具有同等地位的生产要素。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "平台经济时代;数字中国战略时代;新质生产力时代;电子商务时代",
    id: 497192,
    content: "我国数字经济发展的萌芽期可以称为（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCDE",
    choose: "互联网;区块链;云计算;大数据;5G",
    id: 497193,
    content: "下列哪些技术属于数字技术（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 497194,
    content: "1994年5月15日，中国实现了与互联网的全功能连接。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497195,
    content: "2006年我国网络零售额突破1千亿大关。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "设定明确的目标;招聘最优秀的人才;制定严格的规章制度;提供高薪福利",
    id: 497293,
    content: "打造优秀团队的首要步骤是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "单向沟通;双向沟通;无沟通;间接沟通",
    id: 497294,
    content: "在团队建设中，哪种沟通方式最有效（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "定期团队培训;各自独立完成任务;竞争而非合作;无规律的团队活动",
    id: 497295,
    content: "为了增强团队凝聚力，以下哪项活动最有效（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "良好的沟通能力;决策能力;激励团队的能力;独裁和控制欲",
    id: 497296,
    content: "以下哪一项不属于优秀的团队领导应具备的特质（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose:
      "明确的团队目标和愿景;成员间的信任和尊重;有效的沟通和协作;高薪水和奖金",
    id: 497297,
    content: "在打造一个优秀团队时，以下哪些要素是关键（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABD",
    choose:
      "设定清晰的绩效指标;提供必要的培训和支持;鼓励团队成员之间的竞争;定期回顾和反馈",
    id: 497298,
    content: "为了提升团队绩效，可以采取以下哪些措施（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 497299,
    content: "打造优秀团队需要每个成员都具备相同的技能和背景。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 497300,
    content: "团队冲突总是有害的，应该尽量避免。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497301,
    content: "在团队建设中，建立信任关系比制定规章制度更重要。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497302,
    content: "优秀的团队文化能够提升团队成员的工作满意度和忠诚度。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "2020年9月;2021年9月;2022年9月;2023年9月",
    id: 497196,
    content:
      "（  ）习近平总书记在黑龙江考察时提出“加快形成新质生产力”这一重大概念。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "黑龙江;天津;湖南;北京",
    id: 497197,
    content:
      "2023年，习近平总书记在（  ）考察时首次提出“新质生产力”，为新时代新征程加快科技创新、推动高质量发展提供了科学指引。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "劳动密集型;生产技术型;技术密集型;政策密集型",
    id: 497198,
    content:
      "我国经济增长要实现高质量发展，需要从传统要素投入驱动转变为创新驱动，实现产业结构从资本密集型向（  ）的升级。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "从严治党;深化改革;扩大开放;开放市场",
    id: 497199,
    content:
      "发展新质生产力，必须进一步全面（  ），形成与之相适应的新型生产关系。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "优质投资;低碳产业;绿色金融;共产党",
    id: 497200,
    content:
      "持续优化支持绿色低碳发展的经济政策工具箱，发挥（  ）的牵引作用，打造高效生态绿色产业集群。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "高速度;高质量;高规格;高普及",
    id: 497201,
    content:
      "党的十八大以来，我们全面贯彻新发展理念，不断深化对我国经济发展阶段性特征和规律的认识，更加强调发展的（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "BCD",
    choose: "高普及;高科技;高效能;高质量",
    id: 497202,
    content: "新质生产力是创新起主导作用，具有（  ）特征。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose:
      "发展新质生产力是马克思主义生产力理论在当代中国的新发展;发展新质生产力是全面贯彻落实新发展理念的具体实践;发展新质生产力是我国实现新旧动能转换和高质量发展的关键;发展新质生产力是为全球创新性可持续发展贡献中国方案",
    id: 497203,
    content:
      "在百年未有之大变局下，加快形成新质生产力，促进新质生产力涌现，事关中国式现代化的全局。其意义在于（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCDE",
    choose: "创新;协调;绿色;开放;共享",
    id: 497204,
    content:
      "（  ）的新发展理念是习近平新时代中国特色社会主义思想的重要内容，是确保我国经济社会持续健康发展的科学理念。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497205,
    content:
      "2023年12月习近平总书记在中央经济工作会议上强调发展新质生产力，首次在经济工作中对新质生产力进行部署。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497206,
    content:
      "2024年1月习近平总书记在主持中央政治局第十一次集体学习时对发展新质生产力进行系统阐述，首次对新质生产力内涵进行界定。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497207,
    content: "推动高质量发展行稳致远，就必须用新的生产力理论指导新的发展实践。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497208,
    content:
      "2024年3月习近平总书记出席全国两会时发表了关于因地制宜发展新质生产力的系列重要讲话，首次对发展新质生产力方法论提出了要求。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 497209,
    content:
      "2023年《政府工作报告》提出，“大力推进现代化产业体系建设，加快发展新质生产力。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497210,
    content:
      "2024年6月24日，习近平总书记在全国科技大会、国家科学技术奖励大会、两院院士大会上发表重要讲话强调“要推动科技创新和产业创新深度融合，助力发展新质生产力”。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "数量增长;质量提升;学历提升;年龄结构优化",
    id: 497303,
    content: "新时代人才高质量发展的核心是什么（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "党的十七大;党的十八大;党的十九届四中全会;党的二十大",
    id: 497304,
    content:
      "党的哪一次会议强调了要尊重知识、尊重人才，并加快人才发展体制机制和政策创新（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose:
      "降低国内人才流动壁垒;打造低素质劳动力队伍;吸引和集聚全球顶尖人才;减少对国际人才的依赖",
    id: 497305,
    content: "以下哪一项是新时代人才强国战略的重要目标（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose:
      "党组织直接管理所有人才;党组织在人才工作中发挥领导核心作用;党组织决定人才的所有评价和使用;党组织不参与人才的具体事务",
    id: 497306,
    content: "“党管人才”原则的核心要义是什么（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "创新性;开放性;协同性;高效性;数量性",
    id: 497307,
    content: "新时代人才高质量发展的主要特征包括哪些（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCE",
    choose:
      "确保人才工作的正确方向;统筹协调各方资源;提升人才政策的执行力;直接参与人才的具体事务管理;促进人才队伍的团结和稳定",
    id: 497308,
    content: "“党管人才”原则在推动人才高质量发展中的重要作用包括（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 497309,
    content: "新时代人才高质量发展的关键是提高人才的学历门槛。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497310,
    content:
      "我国在推进人才强国战略时，面临着国际竞争加剧和高端人才争夺激烈的挑战。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 497311,
    content:
      "近年来我国在人才培养、引进和使用方面的主要政策和措施包括提高人才引进的门槛。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 497312,
    content: "新时代推动人才高质量发展的主要驱动力是科技创新。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "法律部门;法律体系;司法机关;司法体系",
    id: 517067,
    content:
      "一国全部现行法律规范分类组合为不同的法律部门而形成的有机统一整体是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose:
      "坚持中国共产党的领导;法律的基础和目标不同;法治与政治的关系不同;法律体系的演变与发展不同",
    id: 517068,
    content: "中国特色社会主义法治与西方资本主义法治的最大区别是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "违法行政;滥用职权;行政不作为;以权谋私",
    id: 517069,
    content: "行政机关没有合法授权而干预民商事纠纷属于（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "规则思维;公平思维;人权保障思维;权力制约监督思维",
    id: 517070,
    content: "习近平法治思想中法治思维的内容包括保护人民权益的（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "国家意志性;权利和义务的一致性;国家强制性;以上都是",
    id: 517071,
    content: "法律的特征（外在特征）包括（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "BCD",
    choose: "法律程序;法律概念;法律原则;法律规则",
    id: 517072,
    content: "一部法律或法典的内容在形式上主要有（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "BC",
    choose:
      "法律草案的起草和修订;法律案的提出、审议、表决与通过;法律的公布;法律的实施与解释",
    id: 517073,
    content: "我国法律的制定程序包括（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose:
      "国家权力机关的监督;国家行政机关的监督;国家司法机关的监督;国家监察机关的监督",
    id: 517074,
    content:
      "法律监督是所有国家机关、社会组织和公民等对法的运行过程的合法性所进行的监督，其中国家监督包括（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 517075,
    content:
      "法治思维的特点是以公平正义为出发点（底线），以合法性为目标，按照法律逻辑、法律价值观和法治精神思考问题。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 517076,
    content: "行政机关如果不能证明自己的行为合法，就视为违法。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 517077,
    content:
      "法律靠国家机器（行政机关、司法机关、军事机关等）的强制力量来保障实施。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 517078,
    content: "习近平法治思想中法治思维的内容包括宪法法律至上的程序思维。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 517079,
    content:
      "法律体系是一国全部现行法律规范分类组合为不同的法律部门而形成的有机统一整体。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose:
      "推进数字人才队伍建设，提升数字人才素质水平;加快数字基础设施建设，优化数字技术环境;促进数字技术创新应用，推动产业数字化转型;完善数字经济政策体系，构建数字经济发展环境",
    id: 517043,
    content:
      "（  ）是未来一段时间内我国适应数字化转型、打造数字经济新优势的重点工作。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose:
      "数字人才测评工具;数字人才技能标准框架;行业数字技能需求报告;数字人才培养指南",
    id: 517044,
    content: "（  ）是识别、发现和评价数字人才的重要依据。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose:
      "《数字战略(2020－2024)》;数字人才竞争制胜战略;《产业战略:人工智能领域行动》;美国人工智能计划",
    id: 517045,
    content: "以下哪项不是美国推出的数字人才发展战略（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose:
      "全球人才流动计划(GTS);高潜力人才签证(HPI);科技国家签证计划;全球精英签证",
    id: 517046,
    content:
      "加拿大2017年推出（  ），移民局对拥有数据分析、编码、云计算、人工智能和机器学习、数字项目管理等数字技能人才给予优先审理。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose: "实用性和前瞻性;针对性和系统性;开放性和创新性;战略性和可操作性",
    id: 517047,
    content:
      "《加快数字人才培育支撑数字经济发展行动方案（2024—2026年）》具有（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "美国;欧盟;英国;德国",
    id: 517048,
    content:
      "哪些世界主要发达经济体依托各自比较优势，充分挖掘数字经济发展潜力，形成了架构完整、成效显著的政策体系（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABD",
    choose: "数字化;信息化;便捷化;智能化",
    id: 517049,
    content: "（  ）是未来发展的必然趋势。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "BCD",
    choose: "数字数据分析人才;数字管理人才;数字技术研究与开发人才;数字应用人才",
    id: 517050,
    content: "根据职责和专长的不同，数字人才可分为以下核心类别（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 517051,
    content: "我国目前数字人才供给严重短缺，但数字人才分布结构比较均衡。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 517052,
    content:
      "英国2019年推出全球首个“国家继续教育战略”，投入3.5亿欧元财政资金加强职业教育和继续教育，并鼓励企业设立继续教育培训导师。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 517053,
    content:
      "高校作为数字人才培养的摇篮，应优先倾斜资源，加强数字经济核心学科的建设，如计算机科学、软件工程、人工智能等。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 517054,
    content:
      "《2023全球数字技术发展研究报告》显示，我国数字科技人才规模达12.8万人，占全球总量(77.5万人)的16.5%，位居全球第一，是排名第二的美国数量的1.5倍。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "计算硬件性能;算法创新能力;数据存储容量;网络传输速度",
    id: 518679,
    content: "DeepSeek的核心技术优势主要体现在哪个方面（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose:
      "更快的计算速度;更强的上下文理解能力;更大的模型参数量;更低的硬件成本",
    id: 518680,
    content: "以下哪项最能代表DeepSeek在AI领域的技术突破（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose:
      "专用化AI将取代通用AI;模型规模将持续扩大;算法效率将比规模更重要;硬件性能将成为主要瓶颈",
    id: 518681,
    content: "DeepSeek的发展预示着AI未来哪个重要趋势（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "医疗诊断;金融分析;教育辅助;工业制造",
    id: 518682,
    content: "DeepSeek最可能率先在哪个领域实现商业化突破（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABD",
    choose: "模型架构优化;训练方法改进;数据标注技术;推理效率提升",
    id: 518683,
    content: "DeepSeek的技术创新主要体现在哪些方面（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "算力资源限制;数据隐私问题;模型可解释性;商业化路径",
    id: 518684,
    content: "以下哪些是DeepSeek可能面临的挑战（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518685,
    content: "DeepSeek的成功主要依赖于其强大的算力资源。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 518686,
    content: 'DeepSeek的技术突破预示着AI发展将进入"小而精"的时代。',
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518687,
    content: "DeepSeek在计算机视觉领域的表现优于自然语言处理。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518688,
    content: "DeepSeek的商业化成功将主要取决于其技术先进性。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "区块链;人工智能（AI）;云计算;大数据分析",
    id: 518669,
    content: "Deepseek的核心技术主要基于以下哪项技术（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "智能投顾;供应链管理;医疗诊断;智能客服",
    id: 518670,
    content: "Deepseek在金融领域的主要应用场景是什么（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "数据处理速度快;诊断准确性高;成本低;操作简单",
    id: 518671,
    content: "Deepseek在医疗领域的核心技术优势是什么（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "区块链;自然语言处理（NLP）;云计算;大数据分析",
    id: 518672,
    content: "Deepseek在智能客服中的应用主要依赖于以下哪项技术（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "AB",
    choose: "深度学习;自然语言处理（NLP）;区块链;云计算",
    id: 518673,
    content: "以下哪些是Deepseek的核心技术组成部分（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABCD",
    choose: "金融;医疗;教育;零售",
    id: 518674,
    content: "以下哪些领域是Deepseek的主要应用场景（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518675,
    content: "Deepseek的核心技术基于区块链技术。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 518676,
    content: "Deepseek在金融领域的主要应用场景是智能投顾。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518677,
    content: "Deepseek在医疗领域的应用主要依赖于自然语言处理（NLP）技术。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518678,
    content: "Deepseek在智能客服中的应用主要依赖于云计算技术。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "大规模存储;价值转化与流通;低成本采集;高速传输",
    id: 518639,
    content: "数据要素化的核心目标是实现数据的什么（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "数据质量管理;数据安全保护;数据可视化;数据存储优化",
    id: 518640,
    content: "数据治理体系建设中，确保数据一致性和准确性的关键环节是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "云计算;区块链;人工智能;大数据分析",
    id: 518641,
    content: "以下哪项技术是数据要素化中实现数据确权的关键技术（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "数据存储位置;数据重要性和影响程度;数据生成速度;数据格式类型",
    id: 518642,
    content: "根据《数据安全法》，数据分类分级的依据主要是（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose: "元数据管理;数据质量管理;数据安全管理;数据可视化工具",
    id: 518643,
    content: "数据治理体系的核心组成部分包括哪些（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose:
      "数据权属界定模糊;数据交易市场不成熟;数据隐私泄露风险;数据存储成本高昂",
    id: 518644,
    content: "数据要素化过程中面临的主要挑战包括哪些（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518645,
    content: "数据要素化仅需关注数据的商业价值，无需考虑公共价值。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518646,
    content: "数据治理体系建设仅依赖技术工具，无需组织架构调整。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518647,
    content: "数据分类分级的目的是为了优化数据存储效率。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 518648,
    content: "区块链技术可有效解决数据共享中的信任问题。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "传统制造业;人工智能（AI）;劳动力密集型产业;自然资源开发",
    id: 518689,
    content: "以下哪项是“新质生产力”的核心驱动力（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "C",
    choose: "手工纺织业;传统农业灌溉;智能制造与自动化;低端服务业",
    id: 518690,
    content: "AI在新质生产力中的应用主要体现在以下哪个领域（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "A",
    choose: "数据隐私与伦理问题;劳动力成本上升;传统技术过时;自然资源枯竭",
    id: 518691,
    content: "新质生产力的发展面临的主要挑战是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "蒸汽机技术;大数据分析;手工艺传承;传统物流管理",
    id: 518692,
    content: "以下哪项技术是新质生产力的重要支撑（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose: "高效性;智能性;可持续性;劳动力密集性",
    id: 518693,
    content: "新质生产力的特征包括哪些（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose: "优化资源配置;提升自动化水平;降低能源消耗;增加人力依赖",
    id: 518694,
    content: "AI技术在新质生产力中的支撑作用包括（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518695,
    content: "新质生产力包含技术创新和生产关系、组织模式的双重变革。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518696,
    content: "传统要素需与AI等新技术融合，而非被完全替代。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518697,
    content: "AI是辅助工具，仍需人类监督和伦理约束。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 518698,
    content: "技术革新会引发就业结构变化，需关注转型与再培训。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "区块链技术;强化学习;量子计算;虚拟现实",
    id: 518649,
    content: "下列哪项技术被认为是当前人工智能发展的核心趋势之一（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "传统制造业;医疗诊断;金融风控;以上均是",
    id: 518650,
    content: "人工智能在产业变革中应用最显著的领域是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "D",
    choose: "计算资源需求过高;隐私问题;模型可解释性差;以上均是",
    id: 518651,
    content: "以下哪项是生成式大模型（如GPT-4）的主要技术挑战（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "1万元以下;1万元以上10万元以下;10万元以上50万元以下;50万元以上",
    id: 518652,
    content: "推动人工智能伦理治理的关键主体是（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABD",
    choose: "流程自动化;数据驱动决策;劳动力完全替代;个性化服务能力提升",
    id: 518653,
    content: "人工智能推动产业变革的典型特征包括（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABD",
    choose: "高质量数据获取困难;算力成本高昂;算法理论不成熟;安全与伦理风险",
    id: 518654,
    content: "以下哪些是AI产业化落地的关键挑战（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518655,
    content: "深度学习是当前人工智能领域唯一的主导技术。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518656,
    content: "人工智能伦理问题仅涉及技术层面，与法律无关。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 518657,
    content: "边缘计算技术能够有效缓解AI模型的实时性需求。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 518658,
    content: "各国政府均通过专项政策推动AI产业标准化。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "2021年9月1日;2022年11月1日;2023年5月1日;2024年1月1日",
    id: 518659,
    content: "《网络数据安全管理条例》的施行时间是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "数据自由流通;数据安全责任制;数据完全本地化存储;数据无条件共享",
    id: 518660,
    content: "网络数据安全管理的核心原则是（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose:
      "数据跨境自由流动制度;数据出境安全评估制度;数据永久存储制度;数据无条件公开制度",
    id: 518661,
    content: "以下哪项属于《条例》要求的重要制度（  ）。",
    parentid: 0,
  },
  {
    tType: 1,
    answer: "B",
    choose: "1万元以下;上一年度营业额5%以下;100万元以下;5000万元以下",
    id: 518662,
    content: "违反条例规定导致数据泄露，可能面临的罚款金额为（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ABC",
    choose:
      "合法、正当、必要;明确数据使用目的;数据分类分级管理;保障数据自由跨境流动",
    id: 518663,
    content: "《条例》提出的网络数据安全管理基本原则包括（  ）。",
    parentid: 0,
  },
  {
    tType: 2,
    answer: "ACD",
    choose:
      "处理重要数据;数据存储周期超过1年;向境外提供个人信息;处理超过100万人的个人信息",
    id: 518664,
    content: "以下情形需进行数据安全风险评估的是（  ）。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 518665,
    content: "数据分类分级管理是《条例》提出的基本制度之一。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518666,
    content: "处理个人信息必须取得个人单独同意。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "1",
    choose: null,
    id: 518667,
    content: "数据处理者处理重要数据时，应当指定数据安全负责人。",
    parentid: 0,
  },
  {
    tType: 3,
    answer: "0",
    choose: null,
    id: 518668,
    content: "《条例》禁止一切数据出境行为。",
    parentid: 0,
  },
].map((e) => ({ a: e.answer, i: e.choose, q: e.content }));
